# Generated by Django 4.1.5 on 2023-05-21 23:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Doctorant',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nom', models.CharField(max_length=50, null=True)),
                ('prenom', models.CharField(max_length=50, null=True)),
                ('date_de_naissance', models.DateField(help_text='dd-mm-yy')),
                ('lieu_de_naissance', models.CharField(max_length=50, null=True)),
                ('adresse', models.CharField(max_length=150, null=True)),
                ('Telephone', models.IntegerField(null=True)),
                ('adresse_email', models.EmailField(max_length=254)),
                ('num_bac', models.IntegerField(null=True)),
                ('annèe_bac', models.IntegerField(null=True)),
                ('annèe_premiere_inscription', models.IntegerField(null=True)),
                ('Type', models.CharField(choices=[('lmd', 'Lmd'), ('classique', 'Classique')], max_length=10)),
            ],
            options={
                'verbose_name': 'Ajoute Doctorant',
                'verbose_name_plural': 'Ajoute Doctorants',
            },
        ),
        migrations.CreateModel(
            name='Enseignant',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nom', models.CharField(max_length=50, null=True)),
                ('prenom', models.CharField(max_length=50, null=True)),
                ('date_de_naissance', models.DateField()),
                ('lieu_de_naissance', models.CharField(help_text='dd-mm-yy', max_length=50, null=True)),
                ('Telephone', models.IntegerField(null=True)),
                ('adresse_email', models.EmailField(max_length=254)),
                ('Domain_competence', models.CharField(choices=[('mcb', 'Mcb'), ('mca', 'Mca'), ('maa', 'Maa')], default='option1', max_length=10)),
                ('my_field', models.CharField(choices=[('externe', 'Externe'), ('interne', 'Interne')], default='option1', max_length=10)),
                ('user', models.OneToOneField(blank=True, default=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='enseignant', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Ajoute Enseignant',
                'verbose_name_plural': 'Ajoute Enseignants',
            },
        ),
        migrations.CreateModel(
            name='Publication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Titre_Publication', models.CharField(max_length=300, null=True)),
                ('ID_Doctorantt', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='main.doctorant')),
            ],
        ),
        migrations.CreateModel(
            name='Inscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Titre_Sujet', models.CharField(max_length=300, null=True)),
                ('annèe_inscription', models.IntegerField(null=True)),
                ('Taux_Avencement', models.IntegerField(null=True)),
                ('Date_Probable_Soutenance', models.DateField(help_text='dd-mm-yy')),
                ('Observation', models.TextField(null=True)),
                ('ID_Co_Directeur_these', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='co_directeur_inscriptions', to='main.enseignant')),
                ('ID_Directeur_these', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='directeur_inscriptions', to='main.enseignant')),
                ('ID_Doctorant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.doctorant')),
            ],
        ),
    ]
