# Generated by Django 4.2.1 on 2023-05-13 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_customdoctorant_alter_doctorant_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctorant',
            name='my_field',
            field=models.CharField(choices=[('externe', 'Externe'), ('interne', 'Interne')], default='option1', max_length=10),
        ),
        migrations.DeleteModel(
            name='CustomDoctorant',
        ),
    ]
