# Generated by Django 4.2.1 on 2023-05-13 15:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_doctorant_my_field_delete_customdoctorant'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='doctorant',
            name='my_field',
        ),
    ]
