# Generated by Django 4.2.1 on 2023-05-13 18:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_remove_doctorant_my_field'),
    ]

    operations = [
        migrations.RenameField(
            model_name='doctorant',
            old_name='nome',
            new_name='nom',
        ),
    ]
