# Generated by Django 4.2.1 on 2023-05-13 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_rename_nome_doctorant_nom'),
    ]

    operations = [
        migrations.CreateModel(
            name='Enseignenrt',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nom', models.CharField(max_length=50, null=True)),
                ('prenom', models.CharField(max_length=50, null=True)),
                ('date_de_naissance', models.DateField()),
                ('lieu_de_naissance', models.CharField(help_text='dd-mm-yy', max_length=50, null=True)),
                ('Telephone', models.IntegerField(null=True)),
                ('adresse_email', models.EmailField(max_length=254)),
                ('my_field', models.CharField(choices=[('externe', 'Externe'), ('interne', 'Interne')], default='option1', max_length=10)),
            ],
        ),
    ]
