# Generated by Django 4.2.1 on 2023-05-13 19:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_enseignenrt'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Enseignenrt',
            new_name='Enseignant',
        ),
    ]
