# Generated by Django 4.2.1 on 2023-05-13 20:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_inscription'),
    ]

    operations = [
        migrations.AddField(
            model_name='inscription',
            name='ID_Enseignant',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='main.enseignant'),
        ),
    ]
