# Generated by Django 4.2.1 on 2023-05-13 21:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0018_publication'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publication',
            name='Titre_Publication',
            field=models.CharField(max_length=300, null=True),
        ),
    ]
