# Generated by Django 4.2.1 on 2023-05-13 20:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_inscription_id_enseignant'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inscription',
            name='ID_Enseignant',
        ),
        migrations.AddField(
            model_name='inscription',
            name='ID_Co_Directeur_these',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='co_directeur_inscriptions', to='main.enseignant'),
        ),
        migrations.AddField(
            model_name='inscription',
            name='ID_Directeur_these',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='directeur_inscriptions', to='main.enseignant'),
        ),
    ]
