# Generated by Django 4.2.1 on 2023-05-13 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_remove_inscription_id_enseignant_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='inscription',
            name='Taux_Avencement',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='inscription',
            name='Titre_Sujet',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='inscription',
            name='annèe_inscription',
            field=models.IntegerField(null=True),
        ),
    ]
