# Generated by Django 4.2.1 on 2023-05-13 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_alter_inscription_date_probable_soutenance'),
    ]

    operations = [
        migrations.AddField(
            model_name='inscription',
            name='Observation',
            field=models.TextField(null=True),
        ),
    ]
