# Generated by Django 4.2.1 on 2023-05-13 20:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0015_inscription_observation'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='doctorant',
            options={'verbose_name': 'AjouteDoctorant', 'verbose_name_plural': 'AjouteDoctorants'},
        ),
    ]
