# Generated by Django 4.2.1 on 2023-05-13 20:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0016_alter_doctorant_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='doctorant',
            options={'verbose_name': 'Ajoute Doctorant', 'verbose_name_plural': 'Ajoute Doctorants'},
        ),
        migrations.AlterModelOptions(
            name='enseignant',
            options={'verbose_name': 'Ajoute Enseignant', 'verbose_name_plural': 'Ajoute Enseignants'},
        ),
    ]
