# Generated by Django 4.2 on 2023-06-03 15:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0025_alter_enseignant_etablissement'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enseignant',
            name='Etablissement',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='main.etablissement'),
        ),
        migrations.AlterField(
            model_name='etablissement',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
